name: fixer

on: [push, pull_request, pull_request_target]

jobs:
    fixer:
        needs: setup
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply changes
