- uses: stefanzweifel/git-auto-commit-action@v4
  with:
      # Optional, but recommended
      # Defaults to "Apply automatic changes"
      commit_message: Automated Change

      # Optional. Used by `git-commit`.
      # See https://git-scm.com/docs/git-commit#_options
      commit_options: '--no-verify --signoff'

      # Optional local file path to the repository
      # Defaults to the root of the repository
      repository: .

      # Optional commit user and author settings
      commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
      commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

      # Optional. Used by `git-add`
      # See https://git-scm.com/docs/git-add#_options
      add_options: '-u'

      # Optional. Used by `git-push`
      # See https://git-scm.com/docs/git-push#_options
      push_options: '--force'

      # Optional. Disable dirty check and always try to create a commit and push
      skip_dirty_check: true

      # Optional. Skip internal call to `git fetch`
      skip_fetch: true

      # Optional. Prevents the shell from expanding filenames.
      # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
      disable_globbing: true
