name: Angular-RU style guide

on: [push]

jobs:
    build-and-deploy:
        if: "!contains(github.event.head_commit.message , 'ci skip')"

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Run install step
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
              run: |
                  yarn --ignore-engines --frozen-lockfile
                  yarn format
