name: setup

on: [push]

jobs:
    setup:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['14']
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - run: yarn install
            - run: yarn format
